experiments:
  - name: "experiment1"
    num-server-rounds: 3
    fraction-fit: 0.5
    local-epochs: 1

  - name: "experiment2"
    num-server-rounds: 4
    fraction-fit: 0.5
    local-epochs: 2

  - name: "experiment3"
    num-server-rounds: 5
    fraction-fit: 0.5
    local-epochs: 3
